//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketsHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movy()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public int Id { get; set; }
        public string Judul { get; set; }
        public string Genre { get; set; }
        public decimal Harga_tiket { get; set; }
        public int Stok_tiket { get; set; }
        public System.TimeSpan Jam_mulai { get; set; }
        public Nullable<System.DateTime> Tanggal_mulai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
