//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketsHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int Id { get; set; }
        public int Id_pelanggan { get; set; }
        public int Id_film { get; set; }
        public int Jumlah_tiket { get; set; }
        public decimal Total_harga { get; set; }
        public string Status_pembayaran { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual movy movy { get; set; }
    }
}
